### ISSUE TITLE
Some questions about ddd

### ISSUE THREAD

**Issue by ahomez** [jshilong/DDQ#13]
Hi, thanks for this work, I have read the paper and code, and still have some questions:
1. You use NMS in dqs_cfg In ddq_fcn_head.py(L48),   I would like to know if it is possible to use other NMS(like softNMS), to further enhance model performance.
2. In ddq_rcnn_r50_1x.py, you used FPN, and set nums_out=6, I think you use p2-p7.I would like to know how to replace the FPN here with another neck, such as nasfpn which only return p3-p7.
Looking forward to your reply.

**Comment by jshilong** [comment]
Thank you for your interest.

1. Regarding the adoption of softnms, I have not conducted any related experiments, but I intuitively think that it may can not feature improve the model since 0.7 in normal NMS can handle most scenes.

2. Replacing FPN with a heavy encoder can definitely further improve performance(we report results with dyhead in our study). You can also add an extra P2 in other FPN structures.

**Comment by ahomez** [comment]
Thank for your reply, I will try it!
